### ISSUE TITLE
Can we add a link to packagist.org on GitHub?

### ISSUE THREAD

**Issue by gomzyakov** [shirokovnv/innkeeper#1]
I mean in this block:

![image](https://user-images.githubusercontent.com/1460709/184571122-4bda633f-fc75-40c6-ba88-afe1479a84dd.png)

Link to https://packagist.org/packages/shirokovnv/innkeeper

**Comment by shirokovnv** [comment]
Sounds like a good idea. Added.

**Comment by gomzyakov** [comment]
Thanks!
